name: o_spawn_cup
description: ospawn cup

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.3+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  animated_widgets: ^1.1.0
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.0.3
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.13
  cloud_firestore_odm: ^1.0.0-dev.10
  cloud_functions: ^3.2.10
  cupertino_icons: ^1.0.4
  dotted_border: ^2.0.0+2
  dotted_line: ^3.1.0
  equatable: ^2.0.3
  firebase_auth: ^3.3.14
  firebase_core: ^1.14.1
  firebase_storage: ^10.2.12
  flow_builder: ^0.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_cache_manager: ^3.3.0
  flutter_facebook_auth: '^3.5.0'
  flutter_form_bloc: ^0.30.1
  flutter_staggered_animations: "^1.0.0"
  flutter_svg: ^1.0.0
  flutter_svg_provider: ^1.0.2
  flutter_switch: ^0.3.2

  font_awesome_flutter: ^9.1.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.4.1
  google_fonts: ^2.1.0
  google_sign_in: ^5.3.0
  image_picker: ^0.8.4+6
  json_annotation: ^4.4.0
  mailer: ^5.1.0
  network_image_mock: ^2.1.0
  numberpicker: ^2.1.1
  path_provider: ^2.0.9
  shared_preferences: ^2.0.13
  shimmer: ^2.0.0
  steps: ^1.0.1
  transparent_image: ^2.0.0
  very_good_analysis: ^2.4.0


dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.7
  cloud_firestore_odm_generator: ^1.0.0-dev.10
  dart_code_metrics: ^4.13.0
  fake_cloud_firestore: ^1.2.1
  firebase_auth_mocks: ^0.8.4
  firebase_storage_mocks: ^0.5.0
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  google_sign_in_mocks: ^0.2.1
  json_serializable: ^6.1.6
  mockingjay: ^0.3.0
  mocktail: ^0.3.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/
  fonts:
    - family: o_spawn_cup_font
      fonts:
         - asset: assets/fonts/ReadexPro-VariableFont_wght.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
module:
  androidX: true